name: Staffauth
description: A simple plugin for verifying a player's identity
version: 0.5
main: originalalex.github.io.Plugin

commands:
  login:
    description: Login to your account
    permission: staffauth.auth
  register:
    description: Register an email
    permission: staffauth.auth
  changeemail:
    description: Change login email of other players
    permission: staffauth.changeemail
    aliases: [setemail]

permissions:
  staffauth.auth:
    description: Requires the user to login to their account with a given email before being able to interact with the server
  staffauth.changeemail:
    description: Allows the user to change the login email of themselves or others.

